# Generated by Django 3.1.2 on 2021-01-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catecory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTName', models.CharField(max_length=15)),
                ('CTdescripation', models.TextField()),
                ('CtImage', models.ImageField(upload_to='categore/')),
                ('CTperans', models.ForeignKey(blank=True, limit_choices_to={'CTperans__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.catecory')),
            ],
        ),
        migrations.CreateModel(
            name='Prodect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=15, verbose_name='prodect name')),
                ('PRDDEC', models.TextField(blank=True, null=True)),
                ('ImageProdect', models.ImageField(blank=True, null=True, upload_to='prodects/')),
                ('PRDPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('PRDdiscoust', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount price')),
                ('PRDcost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cost')),
                ('PRDcreate', models.DateTimeField(verbose_name='time create')),
                ('PRDslug', models.SlugField(blank=True, null=True)),
                ('PRDnew', models.BooleanField(default=True)),
                ('PRDbest', models.BooleanField(default=True)),
                ('PRDcatogre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.catecory')),
            ],
        ),
        migrations.CreateModel(
            name='ProdectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageProdect', models.ImageField(upload_to='prodects/')),
                ('Iprodect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prodect')),
            ],
        ),
    ]
